apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort  # for local use, would be LoadBalancer in production
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30000
