apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalancer-config
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        upstream frontend_servers {
            least_conn;
            server frontend:80;
        }

        upstream resizing_servers {
            least_conn;
            server resizer:80;
        }

        server {
            listen 80;

            location /images/ {
                # Default upstream server
                set $upstream_server frontend_servers;

                # Check if resizing parameters are present
                if ($arg_width != '') {
                    set $upstream_server resizing_servers;
                }
                if ($arg_height != '') {
                    set $upstream_server resizing_servers;
                }

                # Proxy to the appropriate upstream server
                proxy_pass http://$upstream_server;

                # Proxy headers
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                # Optional: Add a custom header to identify the upstream server
                add_header X-Upstream-Server $upstream_server;
            }

        }
    }
